name: "cache"
on:
  push:
  pull_request:
  schedule:
  - cron: "0 */2 * * *"

jobs:
  nix-build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - name: nixos-22.11 (1)
          channel: nixos-22.11
          id: 1
          os: ubuntu-latest
        - name: nixos-22.11 (2)
          channel: nixos-22.11
          id: 2
          os: ubuntu-latest
        - name: nixos-22.11 (3)
          channel: nixos-22.11
          id: 3
          os: ubuntu-latest
    name: nix-build
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: cachix/install-nix-action@v18
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - uses: cachix/cachix-action@v12
      with:
        name: hmenke
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
        pushFilter: "(-source$|nixpkgs.tar.gz$)"
    - name: Use nix-community cache
      run: |
        cachix use nix-community
    - name: Run nix-build
      run: |
        rev="$(curl -sSfL https://channels.nix.gsc.io/$channel/history-v2 | tac | awk -v "id=$id" 'NR==id {print $1}')"
        nix flake check -L .github/workflows --override-input nixpkgs "github:NixOS/nixpkgs/$rev"
      env:
        channel: '${{ matrix.channel }}'
        id: '${{ matrix.id }}'
